# Generated by Django 3.0.8 on 2020-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200730_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
        migrations.AddField(
            model_name='album',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photo_thumbnail', to='core.Photo'),
        ),
    ]
